### ISSUE TITLE
Draft don't save URL slug

### ISSUE THREAD

**Issue by katzueno** [concretecms/concrete5-legacy#1923]
When you are saving a page version as a draft, URL slug don't get saved but become blank.

Currently, you must set the URL slug right before you publish the page. Otherwise, because URL slug becomes empty, the canonicalized page title will become URL slug. It's kinda annoying.

A few Japanese users requested to fix this issue.

I'm not considering this as a huge deal, but I just wanted to leave as an issue.

Thx

**Comment by c5enlil** [comment]
I remember seeing this as well at one point.  Any chance you remember what c5 version, or any other details.  I'm coming up empty handed at the moment, and wonder if it hasn't been fixed somewhere along the way because I haven't seen it in quite some time?!

**Comment by c5enlil** [comment]
I recall where I saw this type of behavior....  slightly different though...

Give a user access to post/edit a page type in composer.
Restrict said user's access to edit the url slug input.

The url slug wouldn't update with a title input change in composer, therefore the page wouldn't save because the url slug input was empty.

I'll try to recreate this and open another issue or pr if necessary.
